#pragma once
enum class AnimationActionType {
	DIALOG = 0,
	RECTANGLE_TRANSITION = 1,
	TIMED_MOVEMENT = 5,
	CHANGE_ORIENTATION = 10,
	CHANGE_STATE = 11,
	REMOVE_ENTITY = 15,
	ADD_ENTITY = 16,
	PLAY_SOUND = 20,
	NEXT_LEVEL = 30,
	CHANGE_SCREEN = 31
};